global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jetson-orin-flight-computer'
    static_configs:
      - targets: ['orin-416:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'jetson-orin-health'
    static_configs:
      - targets: ['orin-416:9090']
    scrape_interval: 30s
    metrics_path: /health